name: Terraform and Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Provision EC2 Instance with Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform
        with:
          terraform_version: 1.7.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Save EC2 Hostname
        run: echo "::set-output name=ec2_host::$(terraform output ec2_host)"

      - name: Save EC2 Username
        run: echo "::set-output name=ec2_username::$(terraform output ec2_username)"

      - name: Save EC2 SSH Key
        run: echo "::set-output name=ec2_ssh_key::$(terraform output ec2_ssh_key)"
  docker:
    name: Build and Push Docker Image to AWS ECR
    runs-on: self-hosted
    needs: terraform
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: docker build -t my-docker-image .

      - name: Tag Docker Image
        run: docker tag my-docker-image:latest <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/my-docker-image:latest

      - name: Push Docker Image to AWS ECR
        run: docker push <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/my-docker-image:latest

  deploy:
    name: Deploy Docker Image on EC2 Instance
    runs-on: self-hosted
    needs: [terraform, docker]
    steps:
      - name: SSH into EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.terraform.output.ec2_host }}
          username: ${{ steps.terraform.output.ec2_username }}
          key: ${{ secrets.EC2_SSH_KEY }}

      - name: Pull Docker Image from AWS ECR
        run: docker pull <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/my-docker-image:latest

      - name: Run Docker Container
        run: docker run -d -p 80:80 <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/my-docker-image:latest